// ─── Clients ──────────────────────────────────────────────────────────────────
export const mockClients = [
  {
    id: 'cai_mahindra',
    name: 'CAI Mahindra',
    industry: 'Automotive · Retail',
    avatar: 'CM',
    color: 'from-red-500 to-red-700',
    dotColor: 'bg-red-500',
    lightBg: 'bg-red-50',
    lightBorder: 'border-red-200',
    textColor: 'text-red-700',
    monthlyBudget: 50000,
    platforms: ['Meta'],
    accountManager: 'CAI Mahindra Team',
    status: 'healthy',
    retainer: '₹10.0k/mo',
    since: 'Jan 2026',
  }
];

// ─── Campaigns (enriched with all dashboard fields) ───────────────────────────
export const mockCampaigns = [
  {
    id: 11,
    clientId: 'cai_mahindra',
    name: 'CAI MAY PERFORMANCE 2026',
    ad_name: 'CAI MAY PERFORMANCE 2026',
    channel: 'Meta',
    platform: 'Meta',
    product_category: 'XUV 3XO',
    campaign_target: 'Lead Generation',
    audience_type: 'Retargeting',
    ad_format: 'Video',
    start_date: '2026-05-01',
    end_date: '2026-05-31',
    month: 5,
    year: 2026,
    spend: 25400,
    amount_spent: 25400,
    budget: 25400,
    cpc: 3.25,
    ctr: 1.85,
    cpm: 920,
    conv: 210,
    roas: 6.4,
    status: 'active',
    change: 15.2,
    impressions: 2100000,
    clicks: 7815,
    reach: 1250000,
    frequency: 1.6,
    active: true,
  },
  {
    id: 12,
    clientId: 'cai_mahindra',
    name: 'CAI May XUV 7XO Launch',
    ad_name: 'CAI May XUV 7XO Launch',
    channel: 'Meta',
    platform: 'Meta',
    product_category: 'XUV 7XO',
    campaign_target: 'Traffic',
    audience_type: 'Cold',
    ad_format: 'Carousel',
    start_date: '2026-05-05',
    end_date: '2026-05-31',
    month: 5,
    year: 2026,
    spend: 18500,
    amount_spent: 18500,
    budget: 18500,
    cpc: 4.80,
    ctr: 1.42,
    cpm: 680,
    conv: 155,
    roas: 5.8,
    status: 'active',
    change: 11.4,
    impressions: 1650000,
    clicks: 3854,
    reach: 980000,
    frequency: 1.8,
    active: true,
  },
  {
    id: 1,
    clientId: 'cai_mahindra',
    name: 'CAI MARCH BENEFITS 2026',
    ad_name: 'CAI MARCH BENEFITS 2026',
    channel: 'Meta',
    platform: 'Meta',
    product_category: 'XUV 3XO',
    campaign_target: 'Traffic',
    audience_type: 'Retargeting',
    ad_format: 'Video',
    start_date: '2026-03-01',
    end_date: '2026-03-31',
    month: 3,
    year: 2026,
    spend: 13344,
    amount_spent: 13344,
    budget: 13344,
    cpc: 4.14,
    ctr: 0.957,
    cpm: 1040,
    conv: 145,
    roas: 5.8,
    status: 'active',
    change: 12.4,
    impressions: 1480000,
    clicks: 3220,
    reach: 850000,
    frequency: 2.8,
    active: true,
  },
  {
    id: 2,
    clientId: 'cai_mahindra',
    name: 'CAI March 2026 XUV 7XO',
    ad_name: 'CAI March 2026 XUV 7XO',
    channel: 'Meta',
    platform: 'Meta',
    product_category: 'XUV 7XO',
    campaign_target: 'Traffic',
    audience_type: 'Cold',
    ad_format: 'Carousel',
    start_date: '2026-03-01',
    end_date: '2026-03-31',
    month: 3,
    year: 2026,
    spend: 8108,
    amount_spent: 8108,
    budget: 8108,
    cpc: 6.06,
    ctr: 0.897,
    cpm: 718,
    conv: 50,
    roas: 6.2,
    status: 'active',
    change: 8.2,
    impressions: 2590000,
    clicks: 1337,
    reach: 1200000,
    frequency: 2.2,
    active: true,
  },
  {
    id: 3,
    clientId: 'cai_mahindra',
    name: 'Cai_Mahindra_March_XEV_9S_Campaign',
    ad_name: 'Cai_Mahindra_March_XEV_9S_Campaign',
    channel: 'Meta',
    platform: 'Meta',
    product_category: 'XEV 9e',
    campaign_target: 'Awareness',
    audience_type: 'Lookalike',
    ad_format: 'Single Image',
    start_date: '2026-03-01',
    end_date: '2026-03-31',
    month: 3,
    year: 2026,
    spend: 7165,
    amount_spent: 7165,
    budget: 7165,
    cpc: 10.69,
    ctr: 0.827,
    cpm: 451,
    conv: 53,
    roas: 4.8,
    status: 'paused',
    change: 15.7,
    impressions: 1740000,
    clicks: 670,
    reach: 950000,
    frequency: 4.1,
    active: false,
  },
  {
    id: 4,
    clientId: 'cai_mahindra',
    name: 'Cai_Mahindra_XEV_9S_Mk_2026',
    ad_name: 'Cai_Mahindra_XEV_9S_Mk_2026',
    channel: 'Meta',
    platform: 'Meta',
    product_category: 'XEV 9e',
    campaign_target: 'Conversions',
    audience_type: 'Retargeting',
    ad_format: 'Story',
    start_date: '2026-01-15',
    end_date: '2026-03-31',
    month: 3,
    year: 2026,
    spend: 7050,
    amount_spent: 7050,
    budget: 7050,
    cpc: 6.58,
    ctr: 1.11,
    cpm: 518,
    conv: 114,
    roas: 3.1,
    status: 'active',
    change: -5.3,
    impressions: 1950000,
    clicks: 1071,
    reach: 800000,
    frequency: 2.4,
    active: true,
  },
  {
    id: 5,
    clientId: 'cai_mahindra',
    name: 'Cai_Mahindra_XEV_DEC_Mk_2026',
    ad_name: 'Cai_Mahindra_XEV_DEC_Mk_2026',
    channel: 'Meta',
    platform: 'Meta',
    product_category: 'XEV 9e',
    campaign_target: 'Lead Generation',
    audience_type: 'Cold',
    ad_format: 'Video',
    start_date: '2026-02-01',
    end_date: '2026-03-31',
    month: 3,
    year: 2026,
    spend: 6271,
    amount_spent: 6271,
    budget: 6271,
    cpc: 372.9,
    ctr: 0.905,
    cpm: 2387,
    conv: 47,
    roas: 4.1,
    status: 'active',
    change: -3.2,
    impressions: 217000,
    clicks: 1389,
    reach: 120000,
    frequency: 3.2,
    active: true,
  },
  {
    id: 6,
    clientId: 'cai_mahindra',
    name: 'CAI 2026 Commercial JAN MK',
    ad_name: 'CAI 2026 Commercial JAN MK',
    channel: 'Meta',
    platform: 'Meta',
    product_category: 'Bolero',
    campaign_target: 'Awareness',
    audience_type: 'Cold',
    ad_format: 'Single Image',
    start_date: '2026-01-01',
    end_date: '2026-03-31',
    month: 3,
    year: 2026,
    spend: 6116,
    amount_spent: 6116,
    budget: 6116,
    cpc: 62.3,
    ctr: 1.15,
    cpm: 1177,
    conv: 167,
    roas: 4.3,
    status: 'paused',
    change: 6.8,
    impressions: 620000,
    clicks: 11718,
    reach: 380000,
    frequency: 3.1,
    active: false,
  },
  {
    id: 7,
    clientId: 'cai_mahindra',
    name: 'CAI 2026 XUV 7XO',
    ad_name: 'CAI 2026 XUV 7XO',
    channel: 'Meta',
    platform: 'Meta',
    product_category: 'XUV 7XO',
    campaign_target: 'Traffic',
    audience_type: 'Lookalike',
    ad_format: 'Carousel',
    start_date: '2026-02-10',
    end_date: '2026-03-31',
    month: 3,
    year: 2026,
    spend: 5770,
    amount_spent: 5770,
    budget: 5770,
    cpc: 16.5,
    ctr: 1.328,
    cpm: 402,
    conv: 138,
    roas: 5.2,
    status: 'paused',
    change: 21.3,
    impressions: 1020000,
    clicks: 24888,
    reach: 620000,
    frequency: 3.8,
    active: false,
  },
  {
    id: 8,
    clientId: 'cai_mahindra',
    name: 'Mahindra BE 6 Launch — Google Search',
    ad_name: 'Mahindra BE 6 Launch — Google Search',
    channel: 'Google',
    platform: 'Google',
    product_category: 'BE 6',
    campaign_target: 'Conversions',
    audience_type: 'Cold',
    ad_format: 'Search',
    start_date: '2026-03-01',
    end_date: '2026-03-31',
    month: 3,
    year: 2026,
    spend: 9800,
    amount_spent: 9800,
    budget: 10000,
    cpc: 22.4,
    ctr: 2.18,
    cpm: 1860,
    conv: 92,
    roas: 4.6,
    status: 'active',
    change: 9.4,
    impressions: 520000,
    clicks: 4380,
    reach: 410000,
    frequency: 1.3,
    active: true,
  },
  {
    id: 9,
    clientId: 'cai_mahindra',
    name: 'Mahindra XUV — YouTube TrueView',
    ad_name: 'Mahindra XUV — YouTube TrueView',
    channel: 'Google',
    platform: 'Google',
    product_category: 'XUV 7XO',
    campaign_target: 'Awareness',
    audience_type: 'Cold',
    ad_format: 'Video',
    start_date: '2026-02-15',
    end_date: '2026-03-31',
    month: 3,
    year: 2026,
    spend: 4220,
    amount_spent: 4220,
    budget: 5000,
    cpc: 9.8,
    ctr: 1.62,
    cpm: 390,
    conv: 28,
    roas: 2.9,
    status: 'active',
    change: 4.1,
    impressions: 1080000,
    clicks: 4310,
    reach: 890000,
    frequency: 1.2,
    active: true,
  },
  {
    id: 10,
    clientId: 'cai_mahindra',
    name: 'CAI Bolero Retargeting — Meta DPA',
    ad_name: 'CAI Bolero Retargeting — Meta DPA',
    channel: 'Meta',
    platform: 'Meta',
    product_category: 'Bolero',
    campaign_target: 'Conversions',
    audience_type: 'Retargeting',
    ad_format: 'Carousel',
    start_date: '2026-03-10',
    end_date: '2026-03-31',
    month: 3,
    year: 2026,
    spend: 3890,
    amount_spent: 3890,
    budget: 4000,
    cpc: 5.2,
    ctr: 1.74,
    cpm: 620,
    conv: 88,
    roas: 6.8,
    status: 'active',
    change: 18.2,
    impressions: 628000,
    clicks: 748,
    reach: 290000,
    frequency: 2.2,
    active: true,
  },
];

// ─── Prev‐period baseline (for trend arrows — same ads, previous month values) ──
export const mockPrevCampaigns = mockCampaigns.map(c => ({
  ...c,
  id: c.id + 100,
  spend: Math.round(c.spend * (0.85 + Math.random() * 0.2)),
  amount_spent: Math.round(c.amount_spent * (0.85 + Math.random() * 0.2)),
  impressions: Math.round(c.impressions * (0.88 + Math.random() * 0.18)),
  clicks: Math.round(c.clicks * (0.82 + Math.random() * 0.22)),
  reach: Math.round((c.reach || 0) * (0.87 + Math.random() * 0.18)),
  ctr: Number((c.ctr * (0.88 + Math.random() * 0.2)).toFixed(3)),
  cpc: Number((c.cpc * (0.9 + Math.random() * 0.22)).toFixed(2)),
  cpm: Number((c.cpm * (0.9 + Math.random() * 0.18)).toFixed(2)),
}));

// ─── Monthly trend (12 months) ────────────────────────────────────────────────
export const mockMonthlyTrend = [
  { month: 'Apr', spend: 245000, clicks: 18200, ctr: 0.92, cpc: 13.5 },
  { month: 'May', spend: 268000, clicks: 19800, ctr: 0.97, cpc: 13.2 },
  { month: 'Jun', spend: 290000, clicks: 22100, ctr: 1.04, cpc: 13.1 },
  { month: 'Jul', spend: 312000, clicks: 24400, ctr: 1.08, cpc: 12.8 },
  { month: 'Aug', spend: 285000, clicks: 21800, ctr: 1.01, cpc: 13.1 },
  { month: 'Sep', spend: 298000, clicks: 23200, ctr: 1.05, cpc: 12.9 },
  { month: 'Oct', spend: 335000, clicks: 27100, ctr: 1.12, cpc: 12.4 },
  { month: 'Nov', spend: 378000, clicks: 31500, ctr: 1.18, cpc: 12.0 },
  { month: 'Dec', spend: 420000, clicks: 36200, ctr: 1.22, cpc: 11.6 },
  { month: 'Jan', spend: 395000, clicks: 33800, ctr: 1.15, cpc: 11.7 },
  { month: 'Feb', spend: 412000, clicks: 35400, ctr: 1.19, cpc: 11.6 },
  { month: 'Mar', spend: 54054, clicks: 19454, ctr: 1.08, cpc: 2.78 },
];

// ─── Spend trend (30 days) ────────────────────────────────────────────────────
export const mockSpendTrend30Days = Array.from({ length: 30 }, (_, index) => {
  const day = index + 1;
  const spend = 245000 + Math.round(Math.sin(index / 3) * 32000) + index * 4200;
  return {
    date: `2026-04-${String(day).padStart(2, '0')}`,
    spend,
    clicks: Math.round(spend / 42),
    conversions: index % 9 === 0 ? 0 : 92 + Math.round(index * 2.4),
    roas: index % 9 === 0 ? null : Number((3.7 + Math.sin(index / 5) * 0.8).toFixed(2)),
  };
});

// ─── AI Chat helper ───────────────────────────────────────────────────────────
export function buildMockChatResponse(prompt: string, context?: { campaigns?: any[]; clients?: any[]; integrations?: any[]; insight?: string }) {
  const normalizedPrompt = prompt.toLowerCase();
  const genericConversationPatterns = [
    /\bhi\b/i,
    /\bhello\b/i,
    /\bhey\b/i,
    /\bgood\s+(morning|afternoon|evening)\b/i,
    /\bthanks?\b/i,
    /\bthank\s+you\b/i,
    /\bwho\s+are\s+you\b/i,
    /\bwhat\s+can\s+you\s+do\b/i,
  ];
  const metaAnalyticsTerms = [
    'ad',
    'ads',
    'campaign',
    'campaigns',
    'meta',
    'facebook',
    'instagram',
    'spend',
    'budget',
    'cpc',
    'cpl',
    'ctr',
    'cpm',
    'roas',
    'lead',
    'leads',
    'conversion',
    'conversions',
    'click',
    'clicks',
    'impression',
    'impressions',
    'frequency',
    'fatigue',
    'pause',
    'scale',
    'performance',
    'waste',
    'report',
  ];
  const hasAnalyticsTerm = metaAnalyticsTerms.some(term => normalizedPrompt.includes(term));
  if (!hasAnalyticsTerm && genericConversationPatterns.some(pattern => pattern.test(prompt))) {
    if (/\bthanks?\b|\bthank\s+you\b/.test(normalizedPrompt)) {
      return {
        widget: null,
        insight: 'You are welcome. I am here when you want a clean read on CAI Media campaign movement, waste, fatigue, or scaling opportunities.',
      };
    }
    if (/\bwho\s+are\s+you\b|\bwhat\s+can\s+you\s+do\b/.test(normalizedPrompt)) {
      return {
        widget: null,
        insight: 'I am your CAI Media Meta Ads intelligence agent. Ask me about campaign spend, CPL, CTR, CPM, ROAS, frequency, budget waste, or what to pause and scale.',
      };
    }
    return {
      widget: null,
      insight: 'Hi. I am your CAI Media marketing agent. Ask me anything about your Meta Ads campaigns, or tell me which campaign you want me to inspect.',
    };
  }

  const campaigns = context?.campaigns || mockCampaigns;
  const worstCampaigns = [...campaigns]
    .sort((a, b) => (a.roas ?? -1) - (b.roas ?? -1))
    .slice(0, 3);
  const title = normalizedPrompt.includes('best') ? 'Best Campaigns by ROAS' : 'Campaign Performance Summary';
  return {
    widget: {
      chart_type: normalizedPrompt.includes('trend') ? 'line' : 'table',
      title,
      data: normalizedPrompt.includes('trend') ? mockSpendTrend30Days : worstCampaigns,
      config: {
        x_axis: normalizedPrompt.includes('trend') ? 'date' : 'name',
        y_axis: normalizedPrompt.includes('trend') ? 'spend' : 'roas',
        sort: normalizedPrompt.includes('worst') ? 'asc' : 'desc',
      },
      sql: null,
    },
    insight: context?.insight || 'Mock mode is enabled. CAI Mahindra campaigns represent the automotive portfolio in your ad account.',
  };
}

export function parseTargetingFromName(name: string, channel = 'Meta') {
  const norm = String(name || '').toLowerCase();
  
  // 1. Determine Product Category
  let product_category = 'General';
  if (norm.includes('3xo') || norm.includes('3s')) product_category = 'XUV 3XO';
  else if (norm.includes('7xo') || norm.includes('7s')) product_category = 'XUV 7XO';
  else if (norm.includes('9s') || norm.includes('xev')) product_category = 'XEV 9S';
  else if (norm.includes('thar')) product_category = 'Thar';
  else if (norm.includes('scorpio')) product_category = 'Scorpio-N';
  else if (norm.includes('xuv')) product_category = 'XUV700';

  // 2. Determine Optimization Goal (campaign_target)
  let campaign_target = 'Lead Generation';
  if (norm.includes('sale') || norm.includes('conv') || norm.includes('purchase')) campaign_target = 'Conversions';
  else if (norm.includes('traffic') || norm.includes('link') || norm.includes('click') || norm.includes('lead')) campaign_target = 'Traffic';
  else if (norm.includes('brand') || norm.includes('awareness') || norm.includes('reach') || norm.includes('views')) campaign_target = 'Awareness';

  // 3. Determine Audience Type
  let audience_type = 'Cold Audience';
  if (norm.includes('retarget') || norm.includes('rtg') || norm.includes('website') || norm.includes('pixel')) audience_type = 'Retargeting';
  else if (norm.includes('lal') || norm.includes('lookalike') || norm.includes('affinity')) audience_type = 'Lookalike 1-2%';
  else if (norm.includes('broad') || norm.includes('core')) audience_type = 'Broad Core Interest';

  // 4. Determine Ad Format
  let ad_format = 'Single Image';
  if (norm.includes('video') || norm.includes('vid') || norm.includes('reel') || norm.includes('dynamic')) ad_format = 'Video';
  else if (norm.includes('carousel') || norm.includes('slide') || norm.includes('multi')) ad_format = 'Carousel';
  else if (String(channel).toLowerCase().includes('google') || norm.includes('search') || norm.includes('pmax')) ad_format = 'Search Ad';

  return { product_category, campaign_target, audience_type, ad_format };
}
